### ISSUE TITLE
根本用不起来

### ISSUE THREAD

**Issue by yangweijie** [acabin/docphp#1]
第一，没有配置menu 文件，导致菜单里访问不了配置，差评。
第二，没有语言列表，不知道中文对应cn zh-cn 还是zh 要不要区分大小写。
第三，我cmd path里有svn 开启不开启 use svn 都checkout 不下来language。
第四，截图样式差，建议用pop_style插件美化通过html显示

**Comment by garveen** [comment]
1. Added
2. Added
3. Now SVN is not necessary
4. Rejected
