### ISSUE TITLE
mysqli functions are not added in the library.

### ISSUE THREAD

**Issue by dhirnitish** [acabin/docphp#2]
I really like your plugin and i am using it everyday. Can you also add mysqli functions documentation in the plugin as mysql is already deprecated. That would be a huge help.

**Comment by garveen** [comment]
It is a known issue. Most functions in `mysqli` extension should be found by `mysqli.xxx` form, not `mysqli_xxx` form, even in `php.net`. To fix this, I must create a new index, instead of the one from `php.net`. but this will lead to a lot of work, and not in schedule yet.
